# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a2a254223d3e85deb2316bf638577fd426d02b60ec81fb85b2828a27dd2a4ffc9385d5a7baae9c33c3dda445b29771026bf0c9c7909dae0f19ae2ab55b83895

test:
  secret_key_base: e8d4f176d07d6b5baa17ea4a8b4478240b759fdae6cd5955bf8447ca7cff98659ab3b24471a971f4fefb1e8d6154e8dcf9322498b14878e1e0ca3340b7c65731

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
